<?php

namespace AppBundle\Repository;

/**
 * CsvFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsvFileRepository extends \Doctrine\ORM\EntityRepository
{
}
